# Generated by Django 2.2.19 on 2024-07-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(unique=True, verbose_name='ID велосипеда')),
                ('is_free', models.BooleanField(verbose_name='Свободен ли в данный момент')),
            ],
            options={
                'verbose_name': 'Велосипед',
                'verbose_name_plural': 'Велосипед',
            },
        ),
    ]
