# Generated by Django 2.2.19 on 2024-07-10 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bicycle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время начала')),
                ('rent_stop_time', models.DateTimeField(null=True, verbose_name='Время начала')),
                ('bycycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent', to='bicycle.Bicycle', verbose_name='Велосипед')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сессия аренды',
                'verbose_name_plural': 'Сессия аренды',
            },
        ),
    ]
