# Generated by Django 2.2.19 on 2024-07-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bicycle', '0002_rent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='bycycle',
            new_name='bicycle',
        ),
    ]
