# Generated by Django 3.2.25 on 2024-07-11 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bicycle', '0006_auto_20240710_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='bicycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bicycle', to='bicycle.bicycle', verbose_name='Велосипед'),
        ),
    ]
