# Generated by Django 3.2.25 on 2024-07-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rent_now',
            field=models.BooleanField(default=False, verbose_name='С велосипедом ли в данный момент'),
        ),
    ]
