# Generated by Django 3.2.25 on 2024-07-11 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bicycle', '0006_auto_20240710_1705'),
        ('users', '0003_user_rent_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bicycle_now',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bicycle.bicycle', verbose_name='Велосипед'),
        ),
    ]
